### ISSUE TITLE
Some thoughts

### ISSUE THREAD

**Issue by VirtualMaestro** [pshtif/Genome2D-Core#10]
Hi, Peter.
I have some suggestions about simplification for API.
I guess it would be good if functionality of GNodeFactory moved to GNode.
Why? Because all functionality is about creation of GNode. Besides, GNodeFactory is small and static class, so it is not important which class has this functionality. As result we have more intuitive API without unnecessary entities. Also, it is possible to simplified methods, so for example creation of new node could be looks like:
var node:GNode = GNode.get();
Also, there is possible in GNode.get() method implemented pool for nodes (ofcourse), as result, engine makes user to use pool and user even doesn't know about. Later when you invoke 'dispose', method takes back GNode  instance to pool (with pool we save memory and CPU (creation and garbage collector)).

Eventually, it is not so important, but it is good practice to make simplification of  API and do some routine operations automatically.
Ofcourse, it is just my point of view and everything up to you.

In any case Genome2d the best, just tried to help somehow and share my thoughts.
Thank you for huge work!

**Comment by pshtif** [comment]
Quite an old comment, somehow it got unnoticed by me till now since I scan for issues in the main repo and almost never in the submodules. Anyway your proposed changes already happened with the now obsolete GNodeFactory.
